stages:
  - test
  - build

variables:
  PEX_VERSION: "2.1.37"  # Example version of PEX

before_script:
  - pip install -U pip
  - pip install pex==$PEX_VERSION

install_dependencies:
  stage: test
  script:
    - pex --disable-cache -r requirements.txt -o dependencies.pex
  only:
    changes:
      - requirements.txt

run_tests:
  stage: test
  script:
    - python -m pytest test.py
  artifacts:
    paths:
      - tests/
  only:
    changes:
      - test.py

build_wheel:
  stage: build
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
  only:
    changes:
      - test.py  # Assuming test.py changes are sufficient to trigger wheel build
